---
title: "Diagramme_Jessica"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
#Daten laden
happyscore <- read.csv2("./datasets/Happiness_Score_Countries.csv")
happiness_reisen <- read.csv2("./datasets/happiness_reisen.csv")

#Libraries
library(tidyverse)
library(colorspace)
library(ggthemes)
library(ggforce)
library(ggplot2)
library(ggridges)
library(rgdal)
library(dplyr)
library(RColorBrewer)
```

```{r}
#DATENSÄTZE FILTERN

#Nur Europa
happyscore_EU <- filter(happyscore, name %in% c("Germany", "France",  "United Kingdom", "Spain", "Italy", "Poland", "Sweden", "Netherlands", "Finland", "Czech Republic", "Norway", "Austria", "Switzerland", "Hungary", "Denmark", "Romania", "Portugal", "Belgium", "Ireland", "Slovakia", "Greece", "Estonia", "Croatia", "Slovenia", "Bulgaria", "Lithuania", "Latvia", "Cyprus", "Luxembourg", "Malta", "Russia", "Turkey", "Ukraine", "Kazakhstan", "Azerbaijan", "Belarus", "Serbia", "Moldova", "Georgia", "Bosnia And Herzegovina", "Armenia", "Albania", "Latvia", "Montenegro", "Iceland", "Andorra", "Faroe Islands", "Monaco", "Liechtenstein", "San Marino", "Vatican City"))

reisenhappiness <- read.csv2("./datasets/happiness_reisen.csv")

#Nur Europa & nur 2018
happyscore_EU_2018 <- filter(happyscore_EU, year == 2018)

#Nur Deutschland
happyscore_DE <- filter(happyscore, name == "Germany")

#Nur Bulgarien
happyscore_BULG <- filter(happyscore, name == "Bulgaria")

```

```{r}
#DIAGRAMME

#Balkendiagramm: Vergleich Happiness Score nach Ländern (Europa) 
ggplot(happiness_reisen, aes(y = fct_reorder(Land, whr), x = whr)) +
  geom_col(width = 0.5, height = 0.4) +
  theme_classic(14) +
  labs (y = "Happiness Score (in %)",
        x = "Länder",
        title = "Happiness Score Europa", 
        subtitle = "Balkendiagramm")
  
#Liniendiagramm: Happiness Score Deutschland von 2005-2020
ggplot(happyscore_DE) +
  aes(x = year, y = happiness.score) +
  geom_line()

#Liniendiagramm: Happiness Score Bulgarien von 2007-2020
ggplot(happyscore_BULG) +
  aes(x = year, y = happiness.score) +
  geom_line()

#Boxplot: Happiness Score Europa
ggplot(happyscore_EU, aes(happiness.score, fct_reorder(name, happiness.score))) +
  geom_boxplot()
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE, layout="l-body-outset", fig.width=10, fig.height=8}
ggplot(reisenhappiness, aes(y = reisen.person, x = fct_reorder(Land, reisen.person), fill = whr))+
  geom_col(width = 0.8, height = 0.4) +
  scale_fill_viridis_c() +
  coord_flip() +
  theme_light() +
  geom_text(aes(label = reisen.person), size=3, hjust = -0.7, color = "black") +
  labs (x = "Land",
        y = "Anzahl der Reisen p.P. pro Jahr",
      title = "Anzahl der Reisen der Länder Europas nach Happiness Score", 
      subtitle = "Balkendiagramm")
```