---
title: "Diagramme_Elena"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggforce)
library(dplyr)
library(ggridges)
```



```{r cars}
reisenhappiness <- read.csv2("./datasets/happiness + reisen.csv")

```


```{r}
# Data cleaning 

## Top 3 
reisenhappinesstop3 <- filter(reisenhappiness, Land %in% c("Finnland", "Dänemark", "Schweiz"))

## Deutschland
reisenhappinessde <- filter(reisenhappiness, Land == "Deutschland")

## Top 3 und letzte 3
reisenhappinesstopundflop <- filter(reisenhappiness, Land %in% c("Finnland", "Dänemark", "Schweiz", "Griechenland", "Kroatien", "Bulgarien"))

## Letzte drei 
reisenhappinessflop <-filter(reisenhappiness, Land %in% c("Griechenland", "Kroatien", "Bulgarien"))
```


```{r}
#Alle im Vergleich Lollipop
ggplot(reisenhappiness, aes(x = Land, y = Reisende, color = whr, fill = whr))+
  geom_segment( aes(x = Land, xend= Land, y=0, yend= Reisende)) +
  geom_point( size=5, color="red", fill=alpha("orange", 0.3), alpha=0.7, shape=21, stroke=2)
```
```{r}
#Top 3 
ggplot(reisenhappinesstop3, aes(x = fct_reorder(Land, reisen.person), y = reisen.person, fill = whr))+
  geom_col() +
  scale_fill_viridis_c() +
  labs (x = "Top 3 der glücklichsten Länder",
        y = "Anzahl der Reisen p.P. pro Jahr",
      title = "Anzahl der Reisen der glücklichsten Länder in Europa", 
      subtitle = "Balkendiagramm")

#Flop 3 
ggplot(reisenhappinessflop, aes(x = fct_reorder(Land, reisen.person), y = reisen.person, fill = whr))+
  geom_col() +
  scale_fill_viridis_c() +
  labs (x = "Top 3 der unglücklichsten Länder",
        y = "Anzahl der Reisen p.P. pro Jahr",
      title = "Anzahl der Reisen der unglücklichsten Länder in Europa", 
      subtitle = "Balkendiagramm")

```

```{r}
#Letzten 3
ggplot(reisenhappinessflop, aes(x = fct_relevel(Land, "Zypern", "Luxemburg", "Malta"), y = Reisende, color = whr, fill = whr))+
  geom_col()
```

```{r}
#Top 3 und letzten 3 im Vergleich 
ggplot(reisenhappinesstopundflop, aes(x = fct_relevel(Land, "Deutschland", "Frankreich", "Vereinigtes Königreich", "Zypern", "Luxemburg", "Malta"), y = Reisende, color = whr, fill = whr))+
  geom_col()
```

